spring.application.name=Audio-Transcriber
spring.ai.openai.api-key=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
server.port=8082
spring.ai.openai.audio.transcription.base-url=https://api.openai.com
spring.ai.openai.audio.transcription.options.model=whisper-1

spring.ai.openai.audio.transcription.options.response-format=json

